# Generated by Django 5.2.6 on 2026-01-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinsaKadai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='omiyage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='omiyage_images/'),
        ),
        migrations.AddField(
            model_name='omiyage',
            name='taste',
            field=models.CharField(default='とんこつラーメン味', max_length=100),
        ),
    ]
